name: Test Compiler Bug

on:
  push:
  workflow_dispatch:

env:
  HOMEBREW_NO_AUTO_UPDATE: 1
  HOMEBREW_NO_INSTALL_FROM_API: 1

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [12, 13, 14]

    runs-on: macos-${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - run: brew update

      - run: git -C "$(brew --repository Homebrew/core)" checkout 3b4600424022a33c7f49ea0e7aa0082b2a812f93

      - run: brew deps llvm | xargs brew fetch --concurrency=64 llvm

      - run: brew deps llvm | xargs brew install --overwrite llvm

      - run: brew link --force llvm
        if: runner.arch == 'arm64'

      - run: echo "CC=$(brew --prefix llvm)/bin/clang" >>"${GITHUB_ENV}"

      - name: Test Compiler Bug
        run: make test
