name: Test Compiler Bug

on:
  push:
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-14
          - os: macos-15

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Test Compiler Bug
        run: |
          make test
