name: Test Compiler Bug

on:
  push:
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-14
          - os: macos-15

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - run: brew update

      - run: brew deps llvm@17 | xargs brew fetch --concurrency=64 llvm@17

      - run: brew install --overwrite llvm@17

      - run: brew link --force llvm@17

      - run: echo "CC=$(brew --prefix llvm@17)/bin/clang" >>"${GITHUB_ENV}"

      - name: Test Compiler Bug
        run: |
          make test
